// Source of truth for prerendered routes and sitemap entries.
// Mirrors COMPARE_PAIRS in src/lib/comparePairs.ts — keep in sync.
// Re-run `node scripts/build-seo-files.mjs` after editing this list.

export const STATIC_ROUTES = [
  "/",
  "/cost-per-user",
  "/budget-planner",
  "/pricing",
  "/llm-pricing",
  "/terms",
  "/privacy",
  "/contact",
  "/blog",
  "/blog/how-to-calculate-llm-cost-per-user",
  "/blog/ai-api-budget-planning-for-startups",
  "/compare",
];

export const COMPARE_PAIR_SLUGS = [
  // Frontier vs Frontier
  "claude-opus-4-8-vs-gpt-5-5",
  "claude-opus-4-8-vs-gemini-3-1-pro",
  "deepseek-v4-pro-vs-gpt-5-1",
  "deepseek-v4-pro-vs-claude-sonnet-4-6",
  "claude-fable-5-vs-gpt-5-5",
  "claude-fable-5-vs-gemini-3-1-pro",
  "claude-fable-5-vs-grok-4",
  "gpt-5-5-vs-claude-opus-4-7",
  "gpt-5-5-vs-gemini-3-1-pro",
  "gpt-5-5-vs-grok-4",
  "claude-opus-4-7-vs-gemini-3-1-pro",
  "claude-opus-4-7-vs-grok-4",
  "gemini-3-1-pro-vs-grok-4",
  "claude-opus-4-5-vs-gpt-5-4",
  "claude-sonnet-4-6-vs-gpt-5-1",
  "claude-sonnet-4-6-vs-gemini-3-1-pro",
  "gpt-5-1-vs-claude-sonnet-4-5",
  // New Frontier Models
  "glm-5-2-vs-gpt-5-5",
  "glm-5-2-vs-claude-fable-5",
  "glm-5-2-vs-gpt-5-1",
  "glm-5-2-vs-gpt-5-4",
  "glm-5-2-vs-gemini-2-5-pro",
  "glm-5-2-vs-deepseek-v3-2",
  "glm-5-vs-glm-5-2",
  "glm-5-vs-deepseek-v3-2",
  "claude-fable-5-vs-claude-opus-4-7",
  "claude-fable-5-vs-gpt-5-1",
  // Reasoning Models
  "deepseek-r1-vs-o1",
  "deepseek-r1-vs-o3",
  "o1-vs-o3",
  "o3-vs-o4-mini",
  "o4-mini-vs-claude-sonnet-4-6",
  "o3-vs-claude-opus-4-7",
  "o3-vs-gpt-5-1",
  "o1-vs-claude-3-7-sonnet",
  "o1-vs-gpt-4o",
  // Cheap & Fast
  "gemini-3-5-flash-vs-gpt-4o-mini",
  "gemini-3-5-flash-vs-claude-haiku-4-5",
  "deepseek-v4-flash-vs-gpt-4o-mini",
  "deepseek-v4-flash-vs-gemini-3-5-flash",
  "gpt-4o-mini-vs-claude-3-5-haiku",
  "gpt-4o-mini-vs-gemini-2-5-flash",
  "gpt-4o-mini-vs-claude-haiku-4-5",
  "gpt-4o-mini-vs-gemini-2-0-flash",
  "claude-3-5-haiku-vs-gemini-2-5-flash",
  "claude-haiku-4-5-vs-gemini-2-5-flash",
  "claude-3-5-haiku-vs-deepseek-v3",
  "gemini-2-5-flash-vs-deepseek-v3",
  "claude-3-haiku-vs-claude-3-5-haiku",
  // Open Source vs Hosted
  "deepseek-r1-vs-deepseek-v3",
  "deepseek-v4-pro-vs-deepseek-v4-flash",
  "llama-4-scout-vs-gpt-4o-mini",
  "llama-4-scout-vs-gemini-2-5-flash",
  "llama-3-3-70b-vs-gpt-4o-mini",
  "llama-3-3-70b-vs-claude-3-5-haiku",
  "deepseek-v3-vs-gpt-4o-mini",
  "deepseek-v3-2-vs-gpt-4o-mini",
  "llama-3-1-70b-vs-llama-3-3-70b",
  "mixtral-8x22b-vs-llama-3-3-70b",
  "qwen-2-5-72b-vs-llama-3-3-70b",
  "qwen-2-5-72b-vs-deepseek-v3",
  // OpenAI Lineup
  "gpt-5-5-vs-gpt-5-4",
  "gpt-5-5-vs-gpt-5-1",
  "gpt-5-4-vs-gpt-5-2",
  "gpt-5-2-vs-gpt-5-1",
  "gpt-5-1-vs-gpt-5",
  "gpt-5-vs-gpt-4o",
  "gpt-4o-vs-gpt-4o-mini",
  "gpt-4o-vs-gpt-4-turbo",
  // Anthropic Lineup
  "claude-opus-4-8-vs-claude-opus-4-7",
  "claude-fable-5-vs-claude-sonnet-4-6",
  "claude-opus-4-7-vs-claude-sonnet-4-6",
  "claude-sonnet-4-6-vs-claude-3-7-sonnet",
  "claude-3-7-sonnet-vs-claude-3-5-haiku",
  "claude-3-7-sonnet-vs-claude-haiku-4-5",
  "claude-haiku-4-5-vs-claude-3-5-haiku",
  // Google Lineup
  "gemini-3-5-flash-vs-gemini-2-5-flash",
  "gemini-3-1-pro-vs-gemini-2-5-pro",
  "gemini-2-5-pro-vs-gemini-2-5-flash",
  "gemini-2-5-flash-vs-gemini-2-0-flash",
  // Meta Lineup
  "llama-4-scout-vs-llama-4-maverick",
  "llama-3-1-70b-vs-llama-3-1-8b",
  // Specialty
  "mistral-medium-3-1-vs-gpt-4o-mini",
  "mistral-medium-3-1-vs-mistral-large",
  "mistral-large-vs-mixtral-8x22b",
  "command-r-plus-vs-gpt-4o",
  "sonar-vs-gpt-4o-mini",
  "grok-4-3-vs-gpt-5-1",
  "grok-4-vs-claude-sonnet-4-6",
  "llama-4-maverick-vs-gpt-4o-mini",
];

export const COMPARE_ROUTES = COMPARE_PAIR_SLUGS.map((s) => `/compare/${s}`);

export const ALL_ROUTES = [...STATIC_ROUTES, ...COMPARE_ROUTES];
