import { calcCallCost } from "@/lib/calculator";
import type { ModelPrice } from "@/lib/pricing";

export type AcquisitionToolSlug =
  | "ai-saas-power-user-calculator"
  | "ai-credits-pricing-calculator"
  | "llm-usage-limit-calculator"
  | "llm-fallback-chain-cost-calculator"
  | "llm-conversation-context-cost-calculator"
  | "prompt-caching-break-even-calculator"
  | "ai-feature-profitability-calculator"
  | "llm-price-change-impact-calculator";

export type ToolIconName =
  | "users"
  | "coins"
  | "gauge"
  | "git-branch"
  | "messages"
  | "database-zap"
  | "trending-up"
  | "refresh-cw";

export interface ToolField {
  key: string;
  label: string;
  description: string;
  defaultValue: number;
  min: number;
  max?: number;
  step: number;
  prefix?: string;
  suffix?: string;
}

export interface ToolFaq {
  question: string;
  answer: string;
}

export interface AcquisitionToolDefinition {
  slug: AcquisitionToolSlug;
  icon: ToolIconName;
  eyebrow: string;
  title: string;
  shortTitle: string;
  seoTitle: string;
  description: string;
  promise: string;
  uniqueAngle: string;
  fields: ToolField[];
  usesSecondaryModel?: boolean;
  howItWorks: [string, string, string];
  faqs: ToolFaq[];
  related: AcquisitionToolSlug[];
}

export type MetricTone = "default" | "positive" | "warning" | "danger";

export interface ToolMetric {
  label: string;
  value: string;
  note: string;
  tone?: MetricTone;
}

export interface ToolResult {
  score: number;
  scoreLabel: string;
  verdict: string;
  explanation: string;
  metrics: ToolMetric[];
  actions: string[];
}

const numberField = (
  key: string,
  label: string,
  description: string,
  defaultValue: number,
  options: Partial<Pick<ToolField, "min" | "max" | "step" | "prefix" | "suffix">> = {},
): ToolField => ({
  key,
  label,
  description,
  defaultValue,
  min: options.min ?? 0,
  max: options.max,
  step: options.step ?? 1,
  prefix: options.prefix,
  suffix: options.suffix,
});

export const ACQUISITION_TOOLS: AcquisitionToolDefinition[] = [
  {
    slug: "ai-saas-power-user-calculator",
    icon: "users",
    eyebrow: "Customer economics",
    title: "AI SaaS Power User Calculator",
    shortTitle: "Power User Calculator",
    seoTitle: "AI SaaS Power User & Margin Risk Calculator",
    description:
      "See whether heavy users quietly consume the profit generated by the rest of your AI SaaS customers.",
    promise: "Find the exact power-user mix your current pricing can survive.",
    uniqueAngle:
      "Average usage hides margin risk. This calculator models normal and power users as separate economic cohorts.",
    fields: [
      numberField("monthlyPrice", "Monthly plan price", "Revenue collected per customer each month.", 29, { prefix: "$", step: 1 }),
      numberField("normalCallsPerDay", "Normal-user calls per day", "Average daily AI actions for a typical active customer.", 6, { step: 0.5 }),
      numberField("inputTokens", "Input tokens per call", "Prompt, context, history, and tool definitions.", 1200, { step: 100, suffix: "tokens" }),
      numberField("outputTokens", "Output tokens per call", "Average generated response length.", 400, { step: 50, suffix: "tokens" }),
      numberField("otherCosts", "Other cost per customer", "Hosting, support, storage, and non-LLM variable costs.", 2, { prefix: "$", step: 0.25 }),
      numberField("powerMultiplier", "Power-user usage multiplier", "How much more a heavy customer uses than a normal customer.", 8, { min: 1, max: 100, step: 0.5, suffix: "×" }),
      numberField("powerShare", "Power users in customer base", "Share of customers behaving like power users.", 10, { max: 100, step: 1, suffix: "%" }),
      numberField("targetMargin", "Target gross margin", "Your minimum acceptable gross margin.", 70, { max: 99, step: 1, suffix: "%" }),
    ],
    howItWorks: [
      "Calculate the LLM and non-LLM cost of a normal customer.",
      "Apply your power-user multiplier to create a heavy-usage cohort.",
      "Blend both cohorts and find the customer mix your target margin can tolerate.",
    ],
    faqs: [
      { question: "Why are averages dangerous for AI SaaS pricing?", answer: "A small group of high-usage customers can account for most inference spend. An average can look healthy even when every power user is unprofitable." },
      { question: "What is a healthy power-user margin?", answer: "The right threshold depends on your acquisition and support costs, but every cohort should ideally remain contribution-positive before fixed operating expenses." },
      { question: "How can I reduce power-user risk?", answer: "Use credits, fair-use limits, paid overages, caching, cheaper routing, or a separate high-usage tier instead of subsidizing unlimited consumption." },
    ],
    related: ["ai-credits-pricing-calculator", "llm-usage-limit-calculator", "ai-feature-profitability-calculator"],
  },
  {
    slug: "ai-credits-pricing-calculator",
    icon: "coins",
    eyebrow: "Packaging and monetization",
    title: "AI Credits Pricing Calculator",
    shortTitle: "AI Credits Calculator",
    seoTitle: "AI Credits Pricing Calculator for SaaS Plans",
    description:
      "Convert token costs into customer-friendly credits, safe plan allowances, and profitable top-up packages.",
    promise: "Price one AI credit and decide how many credits each plan should include.",
    uniqueAngle:
      "This starts with real model COGS and works backward into a credit system customers can understand.",
    fields: [
      numberField("planPrice", "Monthly plan price", "Price of the subscription tier that includes credits.", 29, { prefix: "$", step: 1 }),
      numberField("targetMargin", "Target gross margin", "Margin the plan must retain after expected credit use.", 70, { max: 99, step: 1, suffix: "%" }),
      numberField("inputTokens", "Input tokens per credit", "Average input consumed by one credit-bearing action.", 1000, { step: 100, suffix: "tokens" }),
      numberField("outputTokens", "Output tokens per credit", "Average output consumed by one credit-bearing action.", 350, { step: 50, suffix: "tokens" }),
      numberField("otherCostPerAction", "Other cost per action", "Search, image, voice, storage, or third-party API cost.", 0.01, { prefix: "$", step: 0.01 }),
      numberField("includedCredits", "Credits included today", "Current or proposed monthly allowance.", 1000, { step: 50, suffix: "credits" }),
      numberField("breakage", "Expected unused credits", "Percentage of included credits customers will not redeem.", 15, { max: 95, step: 1, suffix: "%" }),
    ],
    howItWorks: [
      "Calculate the underlying cost of one credit-bearing AI action.",
      "Adjust expected usage for credits that expire or remain unused.",
      "Recommend an allowance and top-up price that protect your target margin.",
    ],
    faqs: [
      { question: "How much should one AI credit be worth?", answer: "Tie each credit to a clear customer action, then price it above the expected blended cost of that action rather than exposing raw tokens." },
      { question: "Should unused credits roll over?", answer: "Rollover reduces breakage and increases future cost liability. If credits roll over, use a lower allowance or an expiration window in the model." },
      { question: "How should top-up credits be priced?", answer: "Top-ups should cover the full marginal cost and preserve your target margin. They can cost more per credit than the subscription allowance." },
    ],
    related: ["llm-usage-limit-calculator", "ai-saas-power-user-calculator", "ai-feature-profitability-calculator"],
  },
  {
    slug: "llm-usage-limit-calculator",
    icon: "gauge",
    eyebrow: "Plan guardrails",
    title: "LLM Usage Limit Calculator",
    shortTitle: "Usage Limit Calculator",
    seoTitle: "LLM Usage Limit & AI Message Allowance Calculator",
    description:
      "Calculate how many AI messages, generations, or tasks a monthly plan can safely include.",
    promise: "Set a usage allowance that is generous to customers and safe for gross margin.",
    uniqueAngle:
      "The result is a customer-facing limit and overage price, not another abstract token-cost estimate.",
    fields: [
      numberField("planPrice", "Monthly plan price", "Revenue collected from one customer.", 19, { prefix: "$", step: 1 }),
      numberField("targetMargin", "Target gross margin", "Margin to protect when customers consume their allowance.", 70, { max: 99, step: 1, suffix: "%" }),
      numberField("inputTokens", "Input tokens per action", "Prompt and context used by one message or generation.", 900, { step: 100, suffix: "tokens" }),
      numberField("outputTokens", "Output tokens per action", "Average generated output per action.", 300, { step: 50, suffix: "tokens" }),
      numberField("otherMonthlyCost", "Other monthly COGS", "Hosting, storage, support, and other variable costs per customer.", 1.5, { prefix: "$", step: 0.25 }),
      numberField("activeDays", "Active days per month", "Days on which an active customer typically uses the feature.", 20, { min: 1, max: 31, step: 1, suffix: "days" }),
      numberField("expectedUtilization", "Expected allowance utilization", "Share of the published limit customers are expected to consume.", 75, { min: 1, max: 100, step: 1, suffix: "%" }),
    ],
    howItWorks: [
      "Reserve the portion of plan revenue available for variable costs.",
      "Divide that cost budget by the blended cost of one AI action.",
      "Translate the result into monthly, daily, and expected-utilization allowances.",
    ],
    faqs: [
      { question: "Can I safely offer unlimited AI usage?", answer: "Only when the plan price, model cost, abuse controls, and real usage distribution leave enough margin at extreme consumption levels." },
      { question: "Should limits be daily or monthly?", answer: "Monthly limits are easier to explain, while daily limits reduce burst risk. Many products use a monthly allowance plus a short-term rate limit." },
      { question: "What should I charge for overages?", answer: "The overage price should cover the marginal action cost and preserve the same or a higher gross margin than the base subscription." },
    ],
    related: ["ai-credits-pricing-calculator", "ai-saas-power-user-calculator", "llm-price-change-impact-calculator"],
  },
  {
    slug: "llm-fallback-chain-cost-calculator",
    icon: "git-branch",
    eyebrow: "Reliability economics",
    title: "LLM Fallback Chain Cost Calculator",
    shortTitle: "Fallback Chain Calculator",
    seoTitle: "LLM Fallback, Retry & Cost per Successful Task Calculator",
    description:
      "Price retries and model fallbacks to see what one successful AI task really costs.",
    promise: "Measure reliability cost across primary calls, retries, fallbacks, and failed tasks.",
    uniqueAngle:
      "A cheap request is irrelevant if several attempts are required to produce one accepted result.",
    usesSecondaryModel: true,
    fields: [
      numberField("tasksPerMonth", "Tasks per month", "Completed or attempted customer workflows.", 10000, { step: 100, suffix: "tasks" }),
      numberField("inputTokens", "Input tokens per attempt", "Context sent on each primary, retry, or fallback attempt.", 1800, { step: 100, suffix: "tokens" }),
      numberField("outputTokens", "Output tokens per attempt", "Average generated output for each attempt.", 500, { step: 50, suffix: "tokens" }),
      numberField("primaryFailureRate", "Primary failure rate", "Timeout, invalid-output, safety, or quality rejection rate.", 8, { max: 99, step: 0.5, suffix: "%" }),
      numberField("primaryRetries", "Primary retries", "Maximum times the primary model is retried before fallback.", 1, { max: 10, step: 1 }),
      numberField("fallbackSuccessRate", "Fallback success rate", "Share of fallback attempts that produce an accepted result.", 95, { min: 1, max: 100, step: 1, suffix: "%" }),
      numberField("toolCostPerAttempt", "Tool cost per attempt", "Search, browser, API, or retrieval cost repeated on each attempt.", 0.01, { prefix: "$", step: 0.01 }),
    ],
    howItWorks: [
      "Estimate how many primary attempts occur after accounting for retries.",
      "Price the fallback traffic that survives every primary attempt.",
      "Divide total workflow spend by successful tasks to expose the reliability tax.",
    ],
    faqs: [
      { question: "Why calculate cost per successful task?", answer: "Customers pay for outcomes, while providers bill every attempt. Retries and failures make cost per accepted outcome higher than cost per request." },
      { question: "When should I use a fallback model?", answer: "Fallbacks are useful when they improve completion rates enough to justify added cost and latency. The best chain depends on failure modes, not only model price." },
      { question: "Do retries resend the entire context?", answer: "Often yes. If a retry repeats the original request or accumulated context, it can incur most or all of the original token cost again." },
    ],
    related: ["llm-conversation-context-cost-calculator", "prompt-caching-break-even-calculator", "ai-feature-profitability-calculator"],
  },
  {
    slug: "llm-conversation-context-cost-calculator",
    icon: "messages",
    eyebrow: "Context economics",
    title: "LLM Conversation Context Cost Calculator",
    shortTitle: "Context Cost Calculator",
    seoTitle: "LLM Conversation Context Growth & Chatbot Cost Calculator",
    description:
      "Visualize how repeated chat history, tool definitions, and long conversations compound token spend.",
    promise: "Find the turn where conversation history becomes more expensive than the new message.",
    uniqueAngle:
      "This models billed context turn by turn and compares full history with scheduled summarization.",
    fields: [
      numberField("conversationsPerMonth", "Conversations per month", "Monthly volume of multi-turn sessions.", 10000, { step: 100, suffix: "chats" }),
      numberField("systemPromptTokens", "System prompt tokens", "Instructions included at the start of every model call.", 2000, { step: 100, suffix: "tokens" }),
      numberField("toolSchemaTokens", "Tool-definition tokens", "Function schemas and tool instructions repeated with each call.", 1500, { step: 100, suffix: "tokens" }),
      numberField("userTokens", "User tokens per turn", "Average new user message and retrieved context.", 600, { step: 50, suffix: "tokens" }),
      numberField("assistantTokens", "Assistant tokens per turn", "Average generated response retained in history.", 400, { step: 50, suffix: "tokens" }),
      numberField("turns", "Turns per conversation", "Number of user-assistant exchanges.", 12, { min: 1, max: 200, step: 1, suffix: "turns" }),
      numberField("summarizeEvery", "Summarize every N turns", "How frequently older history is replaced by a compact summary.", 6, { min: 1, max: 100, step: 1, suffix: "turns" }),
      numberField("summaryTokens", "Summary size", "Tokens retained after each history compaction.", 600, { step: 50, suffix: "tokens" }),
      numberField("cacheHit", "Stable-prefix cache hit", "Share of calls receiving discounted system and tool tokens.", 70, { max: 100, step: 1, suffix: "%" }),
    ],
    howItWorks: [
      "Rebuild the full input context for every conversation turn.",
      "Apply prompt-cache pricing to stable system and tool content.",
      "Compare full history with periodic summarization to expose avoidable context spend.",
    ],
    faqs: [
      { question: "Why does conversation cost grow every turn?", answer: "Each model call usually includes prior messages, so old tokens are billed repeatedly while new context continues accumulating." },
      { question: "Does a larger context window reduce cost?", answer: "A larger window prevents truncation but does not make tokens free. Retaining more history can increase spend even when the model accepts it." },
      { question: "When should conversation history be summarized?", answer: "Summarize when the cost and latency of resending raw history exceed the quality value of retaining every message verbatim." },
    ],
    related: ["prompt-caching-break-even-calculator", "llm-fallback-chain-cost-calculator", "llm-usage-limit-calculator"],
  },
  {
    slug: "prompt-caching-break-even-calculator",
    icon: "database-zap",
    eyebrow: "Inference optimization",
    title: "Prompt Caching Break-Even Calculator",
    shortTitle: "Caching Break-Even Calculator",
    seoTitle: "Prompt Caching Break-Even & Savings Calculator",
    description:
      "Calculate whether cache writes, reads, misses, and invalidations make prompt caching worthwhile.",
    promise: "Find the reuse rate and traffic volume required for caching to save money.",
    uniqueAngle:
      "The result includes cache-write premiums and invalidation risk instead of assuming every repeated token is a hit.",
    fields: [
      numberField("prefixTokens", "Cacheable prefix tokens", "Stable system prompt, tools, examples, or document context.", 8000, { step: 100, suffix: "tokens" }),
      numberField("freshTokens", "Fresh input tokens", "Request-specific content that cannot be served from cache.", 2000, { step: 100, suffix: "tokens" }),
      numberField("outputTokens", "Output tokens", "Average generated response per request.", 400, { step: 50, suffix: "tokens" }),
      numberField("requestsPerHour", "Requests per hour", "Average request volume during active periods.", 20, { min: 0.1, step: 1, suffix: "requests" }),
      numberField("activeHoursPerMonth", "Active hours per month", "Hours during which the workload generates requests.", 720, { min: 1, max: 744, step: 1, suffix: "hours" }),
      numberField("cacheHit", "Expected cache-hit rate", "Share of requests that reuse a valid cached prefix.", 85, { max: 100, step: 1, suffix: "%" }),
      numberField("writeMultiplier", "Cache-write price multiplier", "Write cost relative to normal input pricing when provider data is unavailable.", 1.25, { min: 0, max: 10, step: 0.05, suffix: "×" }),
      numberField("readMultiplier", "Cache-read price multiplier", "Read cost relative to normal input pricing when provider data is unavailable.", 0.1, { min: 0, max: 1, step: 0.05, suffix: "×" }),
    ],
    howItWorks: [
      "Price the repeated prefix at normal input rates without caching.",
      "Price hits at cache-read rates and misses at cache-write rates.",
      "Compare both scenarios and calculate the minimum reads required per write.",
    ],
    faqs: [
      { question: "When is prompt caching worth it?", answer: "Caching is most valuable when a large, byte-stable prefix is reused several times before expiration or invalidation." },
      { question: "What causes a prompt-cache miss?", answer: "Changes near the beginning of the cached prefix, TTL expiration, provider routing, or unsupported request shapes can force a new cache write." },
      { question: "Do all models charge the same cache rates?", answer: "No. Read discounts, write premiums, minimum prefix sizes, and expiration rules vary by provider and model." },
    ],
    related: ["llm-conversation-context-cost-calculator", "llm-fallback-chain-cost-calculator", "llm-price-change-impact-calculator"],
  },
  {
    slug: "ai-feature-profitability-calculator",
    icon: "trending-up",
    eyebrow: "Feature unit economics",
    title: "AI Feature Profitability Calculator",
    shortTitle: "Feature Profitability Calculator",
    seoTitle: "AI Feature ROI, Pricing & Profitability Calculator",
    description:
      "Decide whether an AI feature should be bundled, metered, sold as an add-on, or redesigned.",
    promise: "Calculate contribution margin and the minimum profitable price for one AI feature.",
    uniqueAngle:
      "It combines AI calls, human review, third-party tools, adoption, and incremental revenue in one feature P&L.",
    fields: [
      numberField("eligibleUsers", "Eligible customers", "Customers who can discover or purchase the feature.", 5000, { step: 100, suffix: "users" }),
      numberField("adoptionRate", "Feature adoption", "Share of eligible customers expected to use the feature.", 25, { max: 100, step: 1, suffix: "%" }),
      numberField("addOnPrice", "Feature price per user", "Monthly add-on revenue, or zero when bundled.", 10, { prefix: "$", step: 1 }),
      numberField("incrementalValue", "Retention or expansion value", "Estimated monthly revenue benefit per adopting customer.", 3, { prefix: "$", step: 0.5 }),
      numberField("callsPerUserMonth", "AI calls per adopter", "Monthly feature usage for one adopting customer.", 40, { step: 1, suffix: "calls" }),
      numberField("inputTokens", "Input tokens per call", "Average prompt and context size.", 1500, { step: 100, suffix: "tokens" }),
      numberField("outputTokens", "Output tokens per call", "Average generated response size.", 500, { step: 50, suffix: "tokens" }),
      numberField("humanReviewRate", "Calls requiring human review", "Percentage of feature calls reviewed or escalated.", 5, { max: 100, step: 1, suffix: "%" }),
      numberField("humanReviewCost", "Human cost per review", "Loaded cost of one review or intervention.", 0.75, { prefix: "$", step: 0.05 }),
      numberField("otherCostPerUser", "Other cost per adopter", "Storage, search, voice, support, or vendor cost each month.", 1, { prefix: "$", step: 0.25 }),
      numberField("targetMargin", "Target feature margin", "Minimum gross margin for the feature itself.", 70, { max: 99, step: 1, suffix: "%" }),
    ],
    howItWorks: [
      "Calculate monthly AI, review, and third-party cost per adopting customer.",
      "Combine direct add-on revenue with estimated retention or expansion value.",
      "Measure feature contribution margin and recommend the minimum profitable price.",
    ],
    faqs: [
      { question: "Should an AI feature be bundled or sold separately?", answer: "Bundle it when the retention or conversion benefit covers usage cost across the whole plan. Meter or sell it separately when adoption and cost are concentrated." },
      { question: "How should human review be included?", answer: "Multiply the number of feature calls by the review rate and loaded cost per review. Even a small escalation rate can exceed model spend." },
      { question: "What is incremental feature value?", answer: "It is the estimated monthly revenue effect from better conversion, retention, expansion, or willingness to pay, allocated per adopting customer." },
    ],
    related: ["ai-credits-pricing-calculator", "ai-saas-power-user-calculator", "llm-fallback-chain-cost-calculator"],
  },
  {
    slug: "llm-price-change-impact-calculator",
    icon: "refresh-cw",
    eyebrow: "Vendor price risk",
    title: "LLM Price Change Impact Calculator",
    shortTitle: "Price Change Calculator",
    seoTitle: "LLM Price Change, Budget & Gross Margin Impact Calculator",
    description:
      "See how a provider price increase or decrease changes annual spend, customer margin, and required SaaS pricing.",
    promise: "Translate a model-price change into the exact action your SaaS business must take.",
    uniqueAngle:
      "Instead of reporting new token prices, this calculates the required plan increase, usage reduction, or model switch.",
    usesSecondaryModel: true,
    fields: [
      numberField("customers", "Active customers", "Customers generating AI usage each month.", 1000, { step: 50, suffix: "customers" }),
      numberField("monthlyPrice", "Monthly price per customer", "Subscription revenue collected per active customer.", 29, { prefix: "$", step: 1 }),
      numberField("callsPerUserMonth", "Calls per customer", "Average monthly LLM calls for one customer.", 150, { step: 5, suffix: "calls" }),
      numberField("inputTokens", "Input tokens per call", "Average prompt and context size.", 1200, { step: 100, suffix: "tokens" }),
      numberField("outputTokens", "Output tokens per call", "Average generated output size.", 400, { step: 50, suffix: "tokens" }),
      numberField("otherCosts", "Other cost per customer", "Non-LLM monthly variable costs.", 1.5, { prefix: "$", step: 0.25 }),
      numberField("priceChange", "Expected model price change", "Positive for an increase and negative for a reduction.", 25, { min: -99, max: 1000, step: 1, suffix: "%" }),
      numberField("targetMargin", "Target gross margin", "Margin to restore after the provider change.", 70, { max: 99, step: 1, suffix: "%" }),
    ],
    howItWorks: [
      "Calculate current customer-level and company-wide model spend.",
      "Apply the provider price change to your real usage profile.",
      "Compare repricing, usage reduction, and an alternative model as mitigation options.",
    ],
    faqs: [
      { question: "How quickly should SaaS pricing react to model-price changes?", answer: "Small changes may be absorbed, but a material impact on gross margin should trigger routing, limits, packaging, or pricing review before renewal cycles lock in losses." },
      { question: "Should I switch models only because one is cheaper?", answer: "No. Compare cost per successful outcome, latency, quality, retries, and migration effort before changing production routing." },
      { question: "Can lower model prices still hurt margin?", answer: "Yes, if lower prices encourage much higher usage or if customer pricing falls faster than your cost per successful result." },
    ],
    related: ["llm-usage-limit-calculator", "prompt-caching-break-even-calculator", "ai-feature-profitability-calculator"],
  },
];

export const ACQUISITION_TOOL_ROUTES = ACQUISITION_TOOLS.map(
  (tool) => `/tools/${tool.slug}`,
);

export function getAcquisitionTool(
  slug: string | undefined,
): AcquisitionToolDefinition | undefined {
  return ACQUISITION_TOOLS.find((tool) => tool.slug === slug);
}

export function defaultValuesForTool(
  tool: AcquisitionToolDefinition,
): Record<string, number> {
  return Object.fromEntries(tool.fields.map((field) => [field.key, field.defaultValue]));
}

function value(values: Record<string, number>, key: string): number {
  const result = values[key];
  return Number.isFinite(result) ? result : 0;
}

function pct(number: number, decimals = 1): string {
  if (!Number.isFinite(number)) return "—";
  return `${number.toFixed(decimals)}%`;
}

function usd(number: number, decimals = 2): string {
  if (!Number.isFinite(number)) return "$—";
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    minimumFractionDigits: decimals,
    maximumFractionDigits: decimals,
  }).format(number);
}

function compact(number: number, decimals = 1): string {
  if (!Number.isFinite(number)) return "—";
  return new Intl.NumberFormat("en-US", {
    notation: "compact",
    maximumFractionDigits: decimals,
  }).format(number);
}

function clamp(number: number, minimum: number, maximum: number): number {
  return Math.min(maximum, Math.max(minimum, number));
}

function scoreFromMargin(margin: number): number {
  return clamp(Math.round(margin), 0, 100);
}

function powerUserResult(
  values: Record<string, number>,
  model: ModelPrice,
): ToolResult {
  const price = value(values, "monthlyPrice");
  const target = value(values, "targetMargin") / 100;
  const share = clamp(value(values, "powerShare") / 100, 0, 1);
  const callCost = calcCallCost(value(values, "inputTokens"), value(values, "outputTokens"), model);
  const normalCost = callCost * value(values, "normalCallsPerDay") * 30 + value(values, "otherCosts");
  const powerCost = callCost * value(values, "normalCallsPerDay") * 30 * value(values, "powerMultiplier") + value(values, "otherCosts");
  const blendedCost = normalCost * (1 - share) + powerCost * share;
  const margin = price > 0 ? ((price - blendedCost) / price) * 100 : 0;
  const marginBudget = price * (1 - target);
  const maxShare = powerCost > normalCost
    ? clamp(((marginBudget - normalCost) / (powerCost - normalCost)) * 100, 0, 100)
    : 100;
  const normalContribution = Math.max(0.0001, price - normalCost);
  const powerLoss = Math.max(0, powerCost - price);
  const subsidyRatio = powerLoss / normalContribution;
  const safeCalls = callCost > 0
    ? Math.max(0, (marginBudget - value(values, "otherCosts")) / (callCost * 30))
    : 0;
  const healthy = margin >= value(values, "targetMargin");

  return {
    score: scoreFromMargin(margin),
    scoreLabel: "Blended gross margin",
    verdict: healthy ? "Your current power-user mix is sustainable." : "Power users are pushing this plan below its target margin.",
    explanation: healthy
      ? `At the modeled ${value(values, "powerShare").toFixed(0)}% power-user share, the plan retains ${pct(margin)} gross margin.`
      : `To preserve ${pct(value(values, "targetMargin"), 0)} margin, power users should remain below ${pct(maxShare)} or move to a higher-usage tier.`,
    metrics: [
      { label: "Normal-user cost", value: usd(normalCost), note: "Monthly variable cost", tone: normalCost < price ? "positive" : "danger" },
      { label: "Power-user cost", value: usd(powerCost), note: `${value(values, "powerMultiplier")}× normal usage`, tone: powerCost < price ? "warning" : "danger" },
      { label: "Maximum power-user share", value: pct(maxShare), note: `At ${pct(value(values, "targetMargin"), 0)} target margin`, tone: maxShare >= value(values, "powerShare") ? "positive" : "danger" },
      { label: "Normal users per loss-making power user", value: subsidyRatio > 0 ? subsidyRatio.toFixed(1) : "0", note: "Profit subsidy required", tone: subsidyRatio > 1 ? "danger" : "positive" },
    ],
    actions: [
      `Use about ${Math.floor(safeCalls)} normal-user calls per day as the safe full-utilization reference point.`,
      powerCost > price ? "Move heavy customers to credits, overages, or a higher plan." : "Keep monitoring the heavy cohort as model usage changes.",
      "Track p50, p95, and p99 customer usage instead of relying on one average.",
    ],
  };
}

function creditsResult(values: Record<string, number>, model: ModelPrice): ToolResult {
  const price = value(values, "planPrice");
  const target = value(values, "targetMargin") / 100;
  const breakage = clamp(value(values, "breakage") / 100, 0, 0.99);
  const unitCost = calcCallCost(value(values, "inputTokens"), value(values, "outputTokens"), model) + value(values, "otherCostPerAction");
  const included = value(values, "includedCredits");
  const redeemed = included * (1 - breakage);
  const expectedCost = redeemed * unitCost;
  const margin = price > 0 ? ((price - expectedCost) / price) * 100 : 0;
  const costBudget = Math.max(0, price * (1 - target));
  const recommendedCredits = unitCost > 0 && 1 - breakage > 0
    ? Math.floor(costBudget / (unitCost * (1 - breakage)))
    : 0;
  const retailValue = included > 0 ? price / included : 0;
  const topUpPrice = unitCost > 0 && 1 - target > 0 ? (unitCost * 100) / (1 - target) : 0;
  const healthy = margin >= value(values, "targetMargin");

  return {
    score: scoreFromMargin(margin),
    scoreLabel: "Expected credit margin",
    verdict: healthy ? "The current credit allowance protects your target margin." : "The current allowance is too generous for this plan price.",
    explanation: `Customers are expected to redeem ${compact(redeemed)} of ${compact(included)} credits, producing ${usd(expectedCost)} in variable cost per subscription.`,
    metrics: [
      { label: "Recommended included credits", value: compact(recommendedCredits, 0), note: `At ${pct(value(values, "targetMargin"), 0)} target margin`, tone: included <= recommendedCredits ? "positive" : "danger" },
      { label: "Cost of one credit", value: usd(unitCost, 4), note: "Underlying AI and tool cost" },
      { label: "Retail value per credit", value: usd(retailValue, 4), note: "Plan price divided by allowance", tone: retailValue > unitCost ? "positive" : "danger" },
      { label: "100-credit top-up", value: usd(topUpPrice), note: "Minimum price at target margin", tone: "positive" },
    ],
    actions: [
      included > recommendedCredits ? `Reduce the allowance toward ${compact(recommendedCredits, 0)} credits or raise the plan price.` : "The current allowance has room before reaching the modeled cost ceiling.",
      `Define one credit as the modeled action costing ${usd(unitCost, 4)} rather than exposing tokens.`,
      "Recalculate with lower breakage if credits roll over or customers learn to consume more efficiently.",
    ],
  };
}

function usageLimitResult(values: Record<string, number>, model: ModelPrice): ToolResult {
  const price = value(values, "planPrice");
  const target = value(values, "targetMargin") / 100;
  const utilization = clamp(value(values, "expectedUtilization") / 100, 0.01, 1);
  const callCost = calcCallCost(value(values, "inputTokens"), value(values, "outputTokens"), model);
  const availableCost = Math.max(0, price * (1 - target) - value(values, "otherMonthlyCost"));
  const guaranteedLimit = callCost > 0 ? Math.floor(availableCost / callCost) : 0;
  const marketedLimit = Math.floor(guaranteedLimit / utilization);
  const dailyLimit = Math.max(0, Math.floor(marketedLimit / Math.max(1, value(values, "activeDays"))));
  const overagePrice = callCost > 0 && 1 - target > 0 ? callCost / (1 - target) : 0;
  const fullUtilizationCost = marketedLimit * callCost + value(values, "otherMonthlyCost");
  const fullMargin = price > 0 ? ((price - fullUtilizationCost) / price) * 100 : 0;
  const safe = availableCost > 0 && guaranteedLimit > 0;

  return {
    score: safe ? clamp(Math.round((guaranteedLimit / Math.max(1, marketedLimit)) * 100), 0, 100) : 0,
    scoreLabel: "Full-utilization safety",
    verdict: safe ? `Publish about ${compact(marketedLimit, 0)} actions per month at the expected utilization rate.` : "This plan has no remaining cost budget for AI usage.",
    explanation: `A guaranteed all-customers-safe limit is ${compact(guaranteedLimit, 0)} actions. The larger published allowance assumes ${pct(value(values, "expectedUtilization"), 0)} average utilization.`,
    metrics: [
      { label: "Published monthly allowance", value: compact(marketedLimit, 0), note: "Expected-utilization limit", tone: "positive" },
      { label: "Guaranteed safe allowance", value: compact(guaranteedLimit, 0), note: "Safe at 100% utilization" },
      { label: "Suggested daily guardrail", value: compact(dailyLimit, 0), note: `Across ${value(values, "activeDays")} active days` },
      { label: "Minimum overage price", value: usd(overagePrice, 4), note: "Per additional action", tone: "positive" },
    ],
    actions: [
      `Use ${compact(guaranteedLimit, 0)} as the hard economic ceiling and ${compact(marketedLimit, 0)} as the monitored allowance.`,
      fullMargin < value(values, "targetMargin") ? `Full use of the marketed limit falls to ${pct(fullMargin)} margin, so enforce overages or throttling.` : "The marketed limit remains within the target at full use.",
      "Pair the monthly allowance with short-term rate limits to control bursts and abuse.",
    ],
  };
}

function fallbackResult(
  values: Record<string, number>,
  primary: ModelPrice,
  fallback: ModelPrice,
): ToolResult {
  const tasks = value(values, "tasksPerMonth");
  const failureRate = clamp(value(values, "primaryFailureRate") / 100, 0, 0.99);
  const retries = Math.max(0, Math.floor(value(values, "primaryRetries")));
  const fallbackSuccess = clamp(value(values, "fallbackSuccessRate") / 100, 0.01, 1);
  const primaryCost = calcCallCost(value(values, "inputTokens"), value(values, "outputTokens"), primary) + value(values, "toolCostPerAttempt");
  const fallbackCost = calcCallCost(value(values, "inputTokens"), value(values, "outputTokens"), fallback) + value(values, "toolCostPerAttempt");
  let expectedPrimaryAttempts = 0;
  for (let attempt = 0; attempt <= retries; attempt += 1) {
    expectedPrimaryAttempts += failureRate ** attempt;
  }
  const fallbackRate = failureRate ** (retries + 1);
  const expectedCostPerTask = expectedPrimaryAttempts * primaryCost + fallbackRate * fallbackCost;
  const successRate = clamp(1 - fallbackRate * (1 - fallbackSuccess), 0.0001, 1);
  const costPerSuccess = expectedCostPerTask / successRate;
  const baselineSpend = tasks * primaryCost;
  const monthlySpend = tasks * expectedCostPerTask;
  const waste = Math.max(0, monthlySpend - baselineSpend);
  const reliabilityTax = primaryCost > 0 ? ((costPerSuccess - primaryCost) / primaryCost) * 100 : 0;

  return {
    score: clamp(Math.round(successRate * 100 - Math.min(40, reliabilityTax / 2)), 0, 100),
    scoreLabel: "Reliability efficiency",
    verdict: reliabilityTax <= 20 ? "The fallback chain adds a manageable reliability premium." : "Retries and fallback materially increase cost per successful task.",
    explanation: `The chain completes ${pct(successRate * 100)} of tasks at ${usd(costPerSuccess, 4)} per successful result, ${pct(reliabilityTax)} above one primary call.`,
    metrics: [
      { label: "Cost per successful task", value: usd(costPerSuccess, 4), note: "All attempts included", tone: reliabilityTax < 20 ? "positive" : "warning" },
      { label: "Monthly chain spend", value: usd(monthlySpend, 0), note: `${compact(tasks, 0)} attempted tasks` },
      { label: "Retry and fallback waste", value: usd(waste, 0), note: "Above one-attempt baseline", tone: waste > baselineSpend * 0.1 ? "danger" : "warning" },
      { label: "Tasks reaching fallback", value: pct(fallbackRate * 100), note: `${fallback.name} traffic` },
    ],
    actions: [
      `Improve the primary acceptance rate before adding more than ${retries} retries.`,
      `Track ${usd(costPerSuccess, 4)} as unit cost—not the ${usd(primaryCost, 4)} headline request cost.`,
      "Separate timeout, malformed-output, policy, and quality failures so each can use the cheapest recovery path.",
    ],
  };
}

function contextResult(values: Record<string, number>, model: ModelPrice): ToolResult {
  const conversations = value(values, "conversationsPerMonth");
  const turns = Math.max(1, Math.floor(value(values, "turns")));
  const summarizeEvery = Math.max(1, Math.floor(value(values, "summarizeEvery")));
  const stableTokens = value(values, "systemPromptTokens") + value(values, "toolSchemaTokens");
  const userTokens = value(values, "userTokens");
  const assistantTokens = value(values, "assistantTokens");
  const summaryTokens = value(values, "summaryTokens");
  const cacheHit = clamp(value(values, "cacheHit") / 100, 0, 1);
  const cacheReadRate = model.cacheReadPricePerMillion ?? model.inputPricePerMillion * 0.1;
  let baselineCost = 0;
  let optimizedCost = 0;
  let firstTurnInput = 0;
  let lastTurnInput = 0;

  for (let turn = 1; turn <= turns; turn += 1) {
    const fullHistoryTokens = (turn - 1) * (userTokens + assistantTokens);
    const stableCost = ((stableTokens * ((1 - cacheHit) * model.inputPricePerMillion + cacheHit * cacheReadRate)) / 1_000_000);
    const outputCost = (assistantTokens * model.outputPricePerMillion) / 1_000_000;
    const baselineInput = stableTokens + fullHistoryTokens + userTokens;
    const completedBlocks = Math.floor((turn - 1) / summarizeEvery);
    const turnsSinceSummary = (turn - 1) % summarizeEvery;
    const compactHistory = completedBlocks > 0 ? summaryTokens : 0;
    const optimizedHistoryTokens = compactHistory + turnsSinceSummary * (userTokens + assistantTokens);
    baselineCost += stableCost + ((fullHistoryTokens + userTokens) * model.inputPricePerMillion) / 1_000_000 + outputCost;
    optimizedCost += stableCost + ((optimizedHistoryTokens + userTokens) * model.inputPricePerMillion) / 1_000_000 + outputCost;
    if (turn === 1) firstTurnInput = baselineInput;
    if (turn === turns) lastTurnInput = baselineInput;
  }

  const monthlyBaseline = baselineCost * conversations;
  const monthlyOptimized = optimizedCost * conversations;
  const savings = Math.max(0, monthlyBaseline - monthlyOptimized);
  const savingsPct = monthlyBaseline > 0 ? (savings / monthlyBaseline) * 100 : 0;
  const growth = firstTurnInput > 0 ? lastTurnInput / firstTurnInput : 1;

  return {
    score: clamp(Math.round(100 - Math.min(100, (growth - 1) * 18)), 0, 100),
    scoreLabel: "Context efficiency",
    verdict: savingsPct >= 10 ? `Summarizing every ${summarizeEvery} turns materially reduces context cost.` : "This conversation profile has limited savings from summarization.",
    explanation: `By turn ${turns}, billed input per request grows to ${compact(lastTurnInput, 0)} tokens—${growth.toFixed(1)}× the first turn.`,
    metrics: [
      { label: "Full-history monthly cost", value: usd(monthlyBaseline, 0), note: `${compact(conversations, 0)} conversations`, tone: savingsPct > 20 ? "danger" : "warning" },
      { label: "Compacted monthly cost", value: usd(monthlyOptimized, 0), note: `Summarize every ${summarizeEvery} turns`, tone: "positive" },
      { label: "Monthly context savings", value: usd(savings, 0), note: pct(savingsPct), tone: "positive" },
      { label: "Last-turn input growth", value: `${growth.toFixed(1)}×`, note: `${compact(lastTurnInput, 0)} billed input tokens`, tone: growth > 3 ? "danger" : "warning" },
    ],
    actions: [
      `Compact history around every ${summarizeEvery} turns and keep summaries near ${compact(summaryTokens, 0)} tokens.`,
      "Keep system prompts and tool schemas byte-stable so the repeated prefix remains cacheable.",
      "Measure cost by complete conversation and successful outcome, not by the first request.",
    ],
  };
}

function cachingResult(values: Record<string, number>, model: ModelPrice): ToolResult {
  const prefixTokens = value(values, "prefixTokens");
  const freshTokens = value(values, "freshTokens");
  const outputTokens = value(values, "outputTokens");
  const requests = value(values, "requestsPerHour") * value(values, "activeHoursPerMonth");
  const hitRate = clamp(value(values, "cacheHit") / 100, 0, 1);
  const normalInputRate = model.inputPricePerMillion;
  const readRate = model.cacheReadPricePerMillion ?? normalInputRate * value(values, "readMultiplier");
  const writeRate = model.cacheWritePricePerMillion ?? normalInputRate * value(values, "writeMultiplier");
  const freshCost = (freshTokens * normalInputRate) / 1_000_000;
  const outputCost = (outputTokens * model.outputPricePerMillion) / 1_000_000;
  const normalPrefixCost = (prefixTokens * normalInputRate) / 1_000_000;
  const readPrefixCost = (prefixTokens * readRate) / 1_000_000;
  const writePrefixCost = (prefixTokens * writeRate) / 1_000_000;
  const withoutCaching = requests * (normalPrefixCost + freshCost + outputCost);
  const withCaching = requests * (hitRate * readPrefixCost + (1 - hitRate) * writePrefixCost + freshCost + outputCost);
  const savings = withoutCaching - withCaching;
  const savingsPct = withoutCaching > 0 ? (savings / withoutCaching) * 100 : 0;
  const denominator = Math.max(0.0000001, normalPrefixCost - readPrefixCost);
  const breakEvenReads = Math.max(0, (writePrefixCost - normalPrefixCost) / denominator);
  const actualReadsPerWrite = hitRate < 1 ? hitRate / Math.max(0.0001, 1 - hitRate) : Number.POSITIVE_INFINITY;
  const worthwhile = savings > 0;

  return {
    score: clamp(Math.round(50 + savingsPct), 0, 100),
    scoreLabel: "Caching value score",
    verdict: worthwhile ? "Prompt caching is economically worthwhile for this workload." : "Cache misses and write premiums outweigh the read discount.",
    explanation: `You model ${actualReadsPerWrite === Number.POSITIVE_INFINITY ? "near-perfect reuse" : `${actualReadsPerWrite.toFixed(1)} reads per write`} versus a ${breakEvenReads.toFixed(1)}-read break-even point.`,
    metrics: [
      { label: "Monthly savings", value: usd(savings, 0), note: pct(savingsPct), tone: worthwhile ? "positive" : "danger" },
      { label: "Without caching", value: usd(withoutCaching, 0), note: `${compact(requests, 0)} requests` },
      { label: "With caching", value: usd(withCaching, 0), note: `${pct(value(values, "cacheHit"), 0)} hit rate`, tone: worthwhile ? "positive" : "warning" },
      { label: "Break-even reads per write", value: breakEvenReads.toFixed(2), note: "Minimum prefix reuse" },
    ],
    actions: [
      worthwhile ? "Protect the stable prefix from dynamic values that invalidate the cache." : "Increase prefix reuse or avoid paying the cache-write premium for low-frequency prompts.",
      "Monitor actual cache-hit rate by model and route rather than assuming every repeated prompt is cached.",
      "Keep fresh user data after the stable cached prefix whenever provider rules allow it.",
    ],
  };
}

function featureResult(values: Record<string, number>, model: ModelPrice): ToolResult {
  const eligible = value(values, "eligibleUsers");
  const adopters = eligible * clamp(value(values, "adoptionRate") / 100, 0, 1);
  const calls = value(values, "callsPerUserMonth");
  const callCost = calcCallCost(value(values, "inputTokens"), value(values, "outputTokens"), model);
  const llmCostPerUser = calls * callCost;
  const reviewCostPerUser = calls * (value(values, "humanReviewRate") / 100) * value(values, "humanReviewCost");
  const totalCostPerUser = llmCostPerUser + reviewCostPerUser + value(values, "otherCostPerUser");
  const revenuePerUser = value(values, "addOnPrice") + value(values, "incrementalValue");
  const contributionPerUser = revenuePerUser - totalCostPerUser;
  const margin = revenuePerUser > 0 ? (contributionPerUser / revenuePerUser) * 100 : -100;
  const monthlyProfit = adopters * contributionPerUser;
  const target = value(values, "targetMargin") / 100;
  const minimumPrice = Math.max(0, totalCostPerUser / Math.max(0.01, 1 - target) - value(values, "incrementalValue"));
  const reviewShare = totalCostPerUser > 0 ? (reviewCostPerUser / totalCostPerUser) * 100 : 0;
  const healthy = contributionPerUser > 0 && margin >= value(values, "targetMargin");

  return {
    score: scoreFromMargin(margin),
    scoreLabel: "Feature contribution margin",
    verdict: healthy ? "The feature supports its own economics at the modeled price." : contributionPerUser > 0 ? "The feature is profitable, but below its target margin." : "The feature loses money for every adopting customer.",
    explanation: `${compact(adopters, 0)} adopters generate ${usd(monthlyProfit, 0)} in monthly contribution after model, review, and other variable costs.`,
    metrics: [
      { label: "Cost per adopter", value: usd(totalCostPerUser), note: `${usd(llmCostPerUser)} AI + ${usd(reviewCostPerUser)} review`, tone: totalCostPerUser < revenuePerUser ? "positive" : "danger" },
      { label: "Monthly feature contribution", value: usd(monthlyProfit, 0), note: `${compact(adopters, 0)} adopters`, tone: monthlyProfit >= 0 ? "positive" : "danger" },
      { label: "Minimum add-on price", value: usd(minimumPrice), note: `At ${pct(value(values, "targetMargin"), 0)} target margin` },
      { label: "Human review share of cost", value: pct(reviewShare), note: "Often larger than model spend", tone: reviewShare > 50 ? "warning" : "default" },
    ],
    actions: [
      value(values, "addOnPrice") < minimumPrice ? `Raise the add-on toward ${usd(minimumPrice)} or reduce cost per adopter.` : "The add-on price clears the modeled minimum.",
      reviewShare > 30 ? "Prioritize reducing review and escalation frequency before optimizing token prices." : "Model and other variable costs are the larger optimization targets.",
      "Validate incremental retention or expansion value with cohort data before treating it as guaranteed revenue.",
    ],
  };
}

function priceChangeResult(
  values: Record<string, number>,
  currentModel: ModelPrice,
  alternativeModel: ModelPrice,
): ToolResult {
  const customers = value(values, "customers");
  const price = value(values, "monthlyPrice");
  const calls = value(values, "callsPerUserMonth");
  const priceChange = value(values, "priceChange") / 100;
  const target = value(values, "targetMargin") / 100;
  const currentCallCost = calcCallCost(value(values, "inputTokens"), value(values, "outputTokens"), currentModel);
  const alternativeCallCost = calcCallCost(value(values, "inputTokens"), value(values, "outputTokens"), alternativeModel);
  const currentUserCost = currentCallCost * calls + value(values, "otherCosts");
  const changedUserCost = currentCallCost * (1 + priceChange) * calls + value(values, "otherCosts");
  const alternativeUserCost = alternativeCallCost * calls + value(values, "otherCosts");
  const currentMargin = price > 0 ? ((price - currentUserCost) / price) * 100 : 0;
  const changedMargin = price > 0 ? ((price - changedUserCost) / price) * 100 : 0;
  const monthlyBudgetDelta = customers * (changedUserCost - currentUserCost);
  const requiredPrice = changedUserCost / Math.max(0.01, 1 - target);
  const costBudget = Math.max(0, price * (1 - target) - value(values, "otherCosts"));
  const maxCallsAfterChange = currentCallCost * (1 + priceChange) > 0
    ? Math.floor(costBudget / (currentCallCost * (1 + priceChange)))
    : 0;
  const alternativeSavings = customers * Math.max(0, changedUserCost - alternativeUserCost);
  const healthy = changedMargin >= value(values, "targetMargin");

  return {
    score: scoreFromMargin(changedMargin),
    scoreLabel: "Post-change gross margin",
    verdict: healthy ? "The plan absorbs the provider price change without missing its margin target." : "The provider change requires repricing, lower usage, or a routing change.",
    explanation: `Gross margin moves from ${pct(currentMargin)} to ${pct(changedMargin)}, changing annual model spend by ${usd(monthlyBudgetDelta * 12, 0)}.`,
    metrics: [
      { label: "Monthly budget change", value: usd(monthlyBudgetDelta, 0), note: `${pct(value(values, "priceChange"), 0)} provider change`, tone: monthlyBudgetDelta <= 0 ? "positive" : "danger" },
      { label: "Required plan price", value: usd(requiredPrice), note: `Restore ${pct(value(values, "targetMargin"), 0)} margin`, tone: requiredPrice <= price ? "positive" : "warning" },
      { label: "Maximum calls at current price", value: compact(maxCallsAfterChange, 0), note: "Per customer per month" },
      { label: "Alternative-model monthly savings", value: usd(alternativeSavings, 0), note: alternativeModel.name, tone: alternativeSavings > 0 ? "positive" : "default" },
    ],
    actions: [
      requiredPrice > price ? `Raise the plan from ${usd(price)} toward ${usd(requiredPrice)} if usage and routing remain unchanged.` : "No plan increase is required to restore the target margin.",
      calls > maxCallsAfterChange ? `Reduce included usage from ${compact(calls, 0)} toward ${compact(maxCallsAfterChange, 0)} calls.` : "The existing call allowance remains inside the modeled cost budget.",
      alternativeSavings > 0 ? `Evaluate ${alternativeModel.name}; it could save about ${usd(alternativeSavings, 0)} per month before quality and migration costs.` : `${alternativeModel.name} is not cheaper for this token mix.`,
    ],
  };
}

export function calculateAcquisitionTool(
  slug: AcquisitionToolSlug,
  values: Record<string, number>,
  primaryModel: ModelPrice,
  secondaryModel?: ModelPrice,
): ToolResult {
  switch (slug) {
    case "ai-saas-power-user-calculator":
      return powerUserResult(values, primaryModel);
    case "ai-credits-pricing-calculator":
      return creditsResult(values, primaryModel);
    case "llm-usage-limit-calculator":
      return usageLimitResult(values, primaryModel);
    case "llm-fallback-chain-cost-calculator":
      return fallbackResult(values, primaryModel, secondaryModel ?? primaryModel);
    case "llm-conversation-context-cost-calculator":
      return contextResult(values, primaryModel);
    case "prompt-caching-break-even-calculator":
      return cachingResult(values, primaryModel);
    case "ai-feature-profitability-calculator":
      return featureResult(values, primaryModel);
    case "llm-price-change-impact-calculator":
      return priceChangeResult(values, primaryModel, secondaryModel ?? primaryModel);
  }
}
